### PR TITLE
Add support for joystick hot swapping

### PR DESCRIPTION
**Pull request by aaronmjacobs**
Fixes issue #17
Tested with Xbox 360, Xbox One, and PS4 controllers, and Cyborg flight stick

### CODE REVIEW

**Comment by elmindreda** [comment]
This duplicates all buttons and axes 2-3 times. Tested with wired Xbox 360 controller and clone.

**Comment by aaronmjacobs** [comment]
The duplicates are being generated by the calls to CFArrayApplyFunction from within addJoystickElement.

Doing some quick testing, it would appear that when the elements were obtained from the properties given by IORegistryEntryCreateCFProperties (using the kIOHIDElementKey key), the children had to be traversed in order to discover all of the joystick elements. This seems to no longer be the case with IOHIDDeviceCopyMatchingElements - it appears to provide all elements in the returned CFArrayRef, making the traversal of the child elements incorrect.

**Comment by aaronmjacobs** [comment]
Having gone back over Apple's documentation, reviewed other projects' handling of IOHIDElements, and doing further testing, it seems that the correct solution is to not recurse over the children. My pushed changes should fix the duplicate buttons and axes.

**Comment by elmindreda** [comment]
Works beautifully.

**Pull request closed without merging**
