### PR TITLE
Implement NSTextInputClient protocol on OS X

### LINKED ISSUE #456: Dead keys not working
I did not test this on another platform yet. I am working with OS X SDK 10.10 and GLFW 3.1.0 at the moment. The documentation states that GLFW character callbacks even support composing characters using dead keys. This is not working. Any other characters are working correctly and correspond to the current locale, but the dead keys are being ignored. My key callback though is being called e.g. with the key code GLFW_KEY_WORLD_1 when pressing the dead key on the left hand to '1' and below 'ESC'.

### PR DESCRIPTION
**Pull request by nether-cat**
This implementation provides support for IME character composition (Fix #456)

### CODE REVIEW

**Comment by nether-cat** [comment]
I have tested my proposal on OS X 10.11.1 with the US layout (e.g. Option+E and following character), the 3-Set Korean layout and the German layout.

**Comment by elmindreda** [comment]
Thank you, will review this and possibly combine with #41.

**Comment by shibukawa** [comment]
Hi guys,

I am testing PR branch. I think the following code is little better.

```diff
diff --git a/src/cocoa_window.m b/src/cocoa_window.m
index 472ca92..9c32798 100644
--- a/src/cocoa_window.m
+++ b/src/cocoa_window.m
@@ -649,7 +649,10 @@ static const NSRange kEmptyRange = {NSNotFound, 0};
 - (NSRect)firstRectForCharacterRange:(NSRange)aRange
                          actualRange:(NSRangePointer)actualRange
 {
-    return NSMakeRect(0, 0, 0, 0);
+    int x, y;
+    _glfwPlatformGetWindowPos(window, &x, &y);
+    const NSRect contentRect = [window->ns.view frame];
+    return NSMakeRect(x, transformY(y+contentRect.size.height), 0, 0);
 }
```

Position (0, 0) means bottom-left corner of the most left display (Mac OS X has logical axis that combines all display workspaces). Even if the application runs on right display, input method window appears on another display. The above code returns left bottom corner position of current window.

screenshot_im

**Comment by nether-cat** [comment]
Sounds and looks good imho.
Didn't think about that. I will try this out :)

**Comment by elmindreda** [comment]
Merged, with @shibukawa's suggestions. Thank you!

**Pull request closed without merging**
