### PR TITLE
Implement compose key for character input

### PR DESCRIPTION
**Pull request by linkmauve**
This commit has been copied almost verbatim from Bryce Harrington’s patch against Weston’s toytoolkit:
https://patchwork.freedesktop.org/patch/114661/

### CODE REVIEW

**Comment by jadahl** [comment]
lgtm.

**Comment by elmindreda** [comment]
> This commit has been copied almost verbatim

`process_key_press` and `getComposeSymbol` are indeed very similar. What license was the code under originally?

**Comment by linkmauve** [comment]
Weston is licensed under MIT, which would require us to copy its header, it’s probably simpler to ask @bryceharrington to allow this code to be released under GLFW’s zlib.

It could also be possible that this code is considered trivial and thus usable without licensing restrictions, as it is the only way to use libxkbcommon, but I’m not absolutely sure about that.

**Comment by elmindreda** [comment]
If you can get it re-licensed, that would be perfect.

**Comment by bryceharrington** [comment]
I am the original author of the patch, and agree to its use under the zlib license.

**Comment by elmindreda** [comment]
@bryceharrington Hello and thank you!

@linkmauve :+1:

**Pull request merged**
