### PR TITLE
Fix #1112: simultaneous key presses being dropped

### LINKED ISSUE #1112: When two keys are pressed at the same time the second callback is delayed
I'm testing this on Xubuntu 17.04 x86_64 and using GLFW from github master from about two months ago. I modified the key callback in the simple example application like this:

```
static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
{    
    struct timespec ts;
    struct tm lts;
    clock_gettime(CLOCK_REALTIME, &ts);
    localtime_r(&ts.tv_sec, &lts);

    char timestamp[32];
    sprintf(timestamp, "%04d-%02d-%02d %02d:%02d:%02d.%03d", lts.tm_year + 1900, lts.tm_mon + 1, 
        lts.tm_mday, lts.tm_hour, lts.tm_min, lts.tm_sec, (int)(ts.tv_nsec / 1000000));

    printf("%s key_callback(%p, %d, %d, %d, %d)\n", timestamp, window, key, scancode, action, mods);

    if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
        glfwSetWindowShouldClose(window, GLFW_TRUE);
}
```

This is what see when I slam down I and L keys down at exact same time:

```
2017-10-29 17:45:29.716 key_callback(0x55f7e199aea0, 73, 31, 1, 0)
2017-10-29 17:45:30.217 key_callback(0x55f7e199aea0, 76, 46, 1, 0)
2017-10-29 17:45:30.267 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.317 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.367 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.417 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.467 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.517 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.567 key_callback(0x55f7e199aea0, 76, 46, 2, 0)
2017-10-29 17:45:30.601 key_callback(0x55f7e199aea0, 73, 31, 0, 0)
2017-10-29 17:45:30.601 key_callback(0x55f7e199aea0, 76, 46, 0, 0)
```

The first callback comes right away, but the second one comes after 500ms delay, at the same time when the repeat callback start coming.

### PR DESCRIPTION
**Pull request by LucaRood**
This improves the mechanism to check for duplicate key press events, by
checking if the event with the same time code actually corresponds to
the same key.

This will correctly process any key known to GLFW, handling simultanous
presses of different keys, while still filtering out duplicate presses
of the same key.

Note that this still does not properly handle keys that are
GLFW_KEY_UNKNOWN, as I am not aware of a good way to check for previous
events on those keys.

### CODE REVIEW

**Comment by smldis** [comment]
Any progress? I am hitting this on Julia GLFW bindings package

**Comment by kiroma** [comment]
What's the status on this?

**Comment by kiroma** [comment]
Update? I think this is far too simple of a fix for a far too annoying of a bug.

**Comment by kiroma** [comment]
update?

**Comment by Brokkonaut** [comment]
Any chance to get this pulled soon?

**Comment by elmindreda** [comment]
Thank you for this PR. This should be fixed now with 9a3664b4a992a5a9b669179098542b0f882dece7, which is based on it.

**Review by hyperdregon — COMMENTED** [review]
love it

**Pull request closed without merging**
