### PR TITLE
Correctly ignore filtered XIM events. Fixes #548

### LINKED ISSUE #548: glfwSetKeyCallback registering key events as char events
Since the last release, as far as I can tell, something went wrong with the key callback function. 
I am running Ubuntu 14.04 with a GTX 970.

This is the output of `nvidia-smi` : 

Mon Jul  6 20:42:28 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 343.19     Driver Version: 343.19         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:01:00.0     N/A |                  N/A |
| 32%   33C    P8    N/A /  N/A |    272MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

My key callback function works perfectly on OS X 10.10, but fails specifically on my ubuntu machine.
I traced through the glfw code to see where the problem was and found that when I would press keys (W, A, S, D, etc.) the event handler found them to be 'chars' within the processEvent function in x11_window.c. 

I managed to solve my issue by checking out to glfw version 3.1.1.

### PR DESCRIPTION
**Pull request by Spasi**
Tested with greek language on OpenSUSE:

*Before*

> // A pressed
0000000e to 1 at 6.463: Character 0x000003b1 (α) with modifiers (with no mods) input
0000000f to 1 at 6.463: Character 0x000003b1 (α) input
// A released

> // ; pressed
00000010 to 1 at 7.483: Key 0x003b Scancode 0x002f (SEMICOLON) (with no mods) was pressed
// ; released
00000011 to 1 at 7.587: Key 0x003b Scancode 0x002f (SEMICOLON) (with no mods) was released
// A pressed
00000012 to 1 at 10.647: Character 0x000003ac (ά) with modifiers (with no mods) input
00000013 to 1 at 10.647: Character 0x000003ac (ά) input
// A released

*After*

> // A pressed
0000000c to 1 at 8.063: Key 0x0041 Scancode 0x0026 (A) (with no mods) was pressed
0000000d to 1 at 8.063: Character 0x000003b1 (α) with modifiers (with no mods) input
0000000e to 1 at 8.063: Character 0x000003b1 (α) input
// A released
0000000f to 1 at 8.143: Key 0x0041 Scancode 0x0026 (A) (with no mods) was released

> // ; pressed
// ; released
// A pressed
00000010 to 1 at 13.463: Character 0x000003ac (ά) with modifiers (with no mods) input
00000011 to 1 at 13.463: Character 0x000003ac (ά) input
// A released

### CODE REVIEW

**Comment by kevinms** [comment]
Thanks for this fix! After a (long overdue) pull, all my ```KeyPress``` events were being ignored. The problem was the wrong ```if (filtered)``` condition.

**Comment by BryceMehring** [comment]
I am also experiencing this issue. This pull request resolved the issue for me!

**Comment by elmindreda** [comment]
It isn't as simple as that, unfortunately. The inverted test of the `filtered` flag wasn't a typo but a workaround for my IM ([ibus](https://en.wikipedia.org/wiki/Intelligent_Input_Bus)) duplicating key events. This worked on my system but apparently didn't generalize. Neither does this fix, however, which discards _all_ key events for dead keys on my system.

See if the `ximfilter` branch resolves this issue for you.

**Comment by Spasi** [comment]
Yes, it works:

> // A pressed
00000006 to 1 at 2.222: Key 0x0041 Scancode 0x0026 (A) (with no mods) was pressed
00000007 to 1 at 2.222: Character 0x000003b1 (α) with modifiers (with no mods) input
00000008 to 1 at 2.222: Character 0x000003b1 (α) input
// A released
00000009 to 1 at 2.310: Key 0x0041 Scancode 0x0026 (A) (with no mods) was released

> // ; pressed
0000000a to 1 at 3.258: Key 0x003b Scancode 0x002f (SEMICOLON) (with no mods) was pressed
// ; released
0000000b to 1 at 3.330: Key 0x003b Scancode 0x002f (SEMICOLON) (with no mods) was released
// A pressed
0000000c to 1 at 3.566: Character 0x000003ac (ά) with modifiers (with no mods) input
0000000d to 1 at 3.566: Character 0x000003ac (ά) input
// A released

The difference is that I'm now getting key callbacks for `;`. Still not getting for the `A` after `;`, but I think this is behavior you're trying to achieve.

**Comment by elmindreda** [comment]
> Still not getting for the A after ;, but I think this is behavior you're trying to achieve.

No, it's not. All keys should always emit key events.

**Comment by Spasi** [comment]
I've updated the PR. The problem on my system seems to be that `XFilterEvent` resets `event->xkey.keycode` to 0, for both the `;` and the `A` after it. The new commit calls `XFilterEvent` after dispatching `_glfwInputKey`.

New output:

> 00000006 to 1 at 2.396: Key 0x003b Scancode 0x002f (SEMICOLON) (with no mods) was pressed
00000007 to 1 at 2.496: Key 0x003b Scancode 0x002f (SEMICOLON) (with no mods) was released
00000008 to 1 at 3.056: Key 0x0041 Scancode 0x0026 (A) (with no mods) was pressed
00000009 to 1 at 3.057: Character 0x000003ac (ά) with modifiers (with no mods) input
0000000a to 1 at 3.057: Character 0x000003ac (ά) input
0000000b to 1 at 3.124: Key 0x0041 Scancode 0x0026 (A) (with no mods) was released

The `window->x11.last` state from the `ximfilter` branch is not necessary with these changes (on my system).

**Comment by elmindreda** [comment]
@Spasi The `window->x11.last` state is only necessary if you are using ibus.

**Comment by elmindreda** [comment]
@Spasi What is `XMODIFIERS` set to on your machine?

**Comment by elmindreda** [comment]
Please try the `ximfilter` branch again.

**Comment by Spasi** [comment]
`XMODIFIERS` is set to `@im=local`. The `ximfilter` branch now has the same output as the last one I posted.

**Comment by elmindreda** [comment]
That sounds very strange. Please verify that you are using 527952102a13d0caad479a75a4385950f10d79d7.

**Comment by Spasi** [comment]
Yes, I'm using that commit. Why is it strange? All the key events are there and the correct character is displayed (`SEMICOLON+A = ά` for the greek language). What should be different?

Also installed ibus and I'm getting the same output.

**Comment by elmindreda** [comment]
My bad. I looked at the wrong output. Thank you for testing!

**Pull request closed without merging**
