### PR TITLE
Replace CGDisplayIOServicePort with a workaround implementation

### PR DESCRIPTION
**Pull request by mhenr18**
This could be cleaned up and refined a bit by comparing more display
attributes when available, but it gets the job done.

### CODE REVIEW

**Comment by jaredjones** [comment]
Lion is also now unsupported even for security updates from Apple.

**Comment by elmindreda** [comment]
Steam still supports 10.6 and the amount of effort required for GLFW to do so is still just a few isolated ifdefs. If it becomes an issue or when Steam removes support I'll drop those lines. Support for 10.6 isn't holding the code back, as far as I can tell. The code uses several of 10.7 features and at least one symbol added in 10.10.

Supporting Windows XP is far more, far nastier work.

**Comment by elmindreda** [comment]
So, #448 might be the first good argument for dropping 10.6 support.

**Comment by jaredjones** [comment]
I understand the desire to want to keep Snow Leopard support, but no one should be using that OS anymore. It's vulnerable to Heartbleed and about 50 other major vulnerabilities that have been patched on OS X since it was supported. World of Warcraft: The largest MMO on the planet doesn't even support Snow Leopard. :)

**Comment by elmindreda** [comment]
I don't have any particular emotional attachment to any version after 10.3; it's just that the effort involved to keep supporting a version still supported by Steam used to be tiny and thus worth it.

**Comment by jaredjones** [comment]
Why don't we just check the operating system and if it's Snow Leopard it can execute the legacy code, however if it's running a newer version it can run this new implementation?

**Pull request closed without merging**
