### PR TITLE
[docs] Migrating to Sass for stylesheets.

### PR DESCRIPTION
**Pull request by siavashserver**
Migrating to Sass for docs as well to unify the workflow.

Related: glfw/website#70
Follow up to : glfw/website#71 and glfw/glfw#1757

### CODE REVIEW

**Comment by linkmauve** [comment]
Since this seems to be done mostly for variables, may I suggest using [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) instead? They don’t require any compilation step, and make it easier to change them at runtime (for instance for a dark theme, if we ever get one in the future).

**Comment by siavashserver** [comment]
I still rather to keep sass/less in my toolchain for stuff like mixins,
etc; they come in handy 😋

In other words sass/less and css vars can coexist and complement each other.

**Comment by linkmauve** [comment]
I see no problem with that! :D

**Comment by elmindreda** [comment]
Merged, thank you!

**Pull request closed without merging**
