### PR TITLE
GLAPIENTRY is unconditionally defined by gl.h

### PR DESCRIPTION
**Pull request by devnexen**
to avoid already defined constant.

### CODE REVIEW

**Comment by elmindreda** [comment]
What is the purpose of this PR?

**Comment by devnexen** [comment]
It does not compile since GLAPIENTRY is define before inclusion of gl.h below which ... defines it

**Comment by elmindreda** [comment]
On what platform is the current order causing a problem?

**Comment by devnexen** [comment]
Openbsd

**Comment by elmindreda** [comment]
This has been merged as 57f872054c1a9eac43866a1b5c42b24f747f66c7 with additional cleanup in be51c201dd171b2c6856f5e4c7986b50bc9a5056.

**Comment by devnexen** [comment]
Thanks for your patience ;-)

**Pull request closed without merging**
