### PR TITLE
Fix a few bugs in MIR

### PR DESCRIPTION
**Pull request by BrandonSchaefer**
* Changed set_type --> set_state
* Give more info back when an error happens with a connection/surface
* Small var name change size --> mirPixelFormats

### CODE REVIEW

**Comment by BrandonSchaefer** [comment]
Urg.. Yeah sorry about that! If you're able to quickly remove that, and the one for the surface that would be awesome :). Otherwise ill get a pull request tomorrow for it!

**Comment by BrandonSchaefer** [comment]
On the diff line 413:
+ mir_surface_release_sync(window->mir.surface);

**Comment by elmindreda** [comment]
Done with 40f7d4fce0c3db679e94cc78dc4fd2481854088b.

**Comment by BrandonSchaefer** [comment]
Awesome, thank you!

**Pull request closed without merging**
