### PR TITLE
Convert defines to enums

### PR DESCRIPTION
**Pull request by Frostie314159**
This PR attempts to migrate most defines to enums.

### CODE REVIEW

**Comment by Frostie314159** [comment]
I just noticed the build errors. They come from a change I made aiming to make function attributes and return values more logical(i.e. uint32_t instead of int in places where it made sense). I'll make a separate PR with those changes sometime soon.

**Comment by elmindreda** [comment]
Thank you for this PR but I will not merge this. The GLFW 3 API needs to remain stable, including the macros the public header provides. The next major version will likely use enums for numerical constants, which will require renaming symbols and changing function parameter types.

**Comment by Frostie314159** [comment]
But with enums nothing should change since they refer to the same value. So this would be non-breaking.

**Comment by Frostie314159** [comment]
> The GLFW 3 API needs to remain stable, including the macros the public header provides. 
I see what you mean, but I tested it with the provided tests and it worked without issues.
This change shouldn't even be noticed by most users.

**Pull request closed without merging**
