### PR TITLE
Added a CMake line to select C99 in the implementation

### PR DESCRIPTION
**Pull request by gracicot**
This tells CMake to select the C99 standard in a compiler/platform agnostic way.

It should fix issue #1560

Reopened from gracicot#1

### CODE REVIEW

**Comment by elmindreda** [comment]
Thank you for all the workaround stuff so this can be merged before bumping the minimum CMake version!

**Comment by tombsar** [comment]
I think this fix only covered the main glfw library, not the tests. I'm still getting errors about C99 code in tests/glfwinfo.c.

**Comment by gracicot** [comment]
@tombsar I'll open a new pull request for that. It should be similar  and as simple as this one. I'll try to check if there is no other targets to change too.

**Comment by elmindreda** [comment]
Thank you!

**Pull request closed without merging**
