### PR TITLE
Added Premake5

### PR DESCRIPTION
**Pull request by afk47**
Added premake5

### CODE REVIEW

**Comment by gracicot** [comment]
Hi! Do you volunteer to support and maintain premake support in GLFW for all versions to come and also add CI for premake?

Also, your changes seem really similar to all the other premake merge request. Is there something different that would make this premake PR more likely to be merged?

**Comment by afk47** [comment]
No my git was misconfigured and made a pr when i tried pushing to my fork

**Comment by gracicot** [comment]
Thanks for letting us know. We received many PR to add premake specifically and it's kind of hard to know why it happen so often. Good to know they may all be accidental.

**Comment by afk47** [comment]
You're welcome!

**Pull request closed without merging**
