### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Luflosi**

### CODE REVIEW

**Comment by Luflosi** [comment]
I referenced the pull request number before this pull request existed. This causes Github to not underline the "Closes" word with the label "This commit closes pull request #1513." in the commit message. Is that a problem?

**Comment by elmindreda** [comment]
It shouldn't be a problem. The important thing (imo) is to have the issue number there to help humans.

**Comment by Luflosi** [comment]
Should I rebase the commit onto the latest master?

**Comment by elmindreda** [comment]
@Luflosi Yes, please do!

**Comment by Luflosi** [comment]
Done.

**Pull request merged**
