### PR TITLE
[docs] Better scaling on mobile and small screens.

### PR DESCRIPTION
**Pull request by siavashserver**
Hopefully the docs will become easier to read on mobile devices.

Related: glfw/website#70
Follow up to : glfw/website#71

### CODE REVIEW

**Comment by elmindreda** [comment]
Some of the elements in the top navigation bars seem to be displaced. Currently they look like this
Screenshot_2020-09-01 GLFW Main Page

With this PR they instead look like this on Firefox and Edge
Screenshot_2020-09-01 GLFW Main Page(1)

Would it be possible to move the three top links to where it matches the rest of the site?

**Comment by siavashserver** [comment]
It should be fixed now; forgot to test on big displays xD

**Review by elmindreda — APPROVED** [review]
👍

**Comment by elmindreda** [comment]
Thank you!

**Comment by siavashserver** [comment]
You're welcome! 😊

**Pull request closed without merging**
