### PR TITLE
Revised PR for add support for querying work area

### PR DESCRIPTION
**Pull request by dougbinks**
This is a revision of PR for Add support for querying work area #989

The implementation has been tested on Windows 10, OS X 10.11.6 and Ubuntu 18.04 with X11. There is a Wayland implementation which returns monitor virtual position and resolution but this is untested.

### CODE REVIEW

**Comment by dougbinks** [comment]
I have now tested this on Wayland on Ubuntu 18.04. Took a little while to get all the dependencies sorted (once glfw wayland support goes out of experimental a guide might be needed), but everything works with no changes to this PR.

**Comment by ocornut** [comment]
Hello,
Any chance getting this included in GLFW 3.3 or are the issues for it already locked down?
The PR looks fairly trivial.
Apologies for the bump.

**Comment by elmindreda** [comment]
@ocornut It should be able to go into 3.3 modulo any unexpected problems. Looks like all of the updates it needs are trivial.

**Comment by elmindreda** [comment]
Thank you! This has been merged with a few additional fixes.

**Comment by ocornut** [comment]
Thank you very much @felselva @dougbinks @elmindreda .

**Pull request closed without merging**
