### PR TITLE
Clipboard

### PR DESCRIPTION
**Pull request by ricardomv**
Hi, i have the clipboard working but i have some issues i would like to understand better. First question is @jadahl do i really need to get the serial from all input to use it to set a selection?
And_glfwPlatformGetClipboardString _glfwPlatformSetClipboardString are not thread safe and i can't find anywhere in the documentation if they should be or not.
BTW @jadahl can you review the patch?

### CODE REVIEW

**Comment by jadahl** [comment]
Sorry for the delay. Thanks for working on this. However, the new clipboard patch seems to not address the all of the raised issues in the previous review, for example this <https://github.com/ricardomv/glfw/commit/a84fe7eb850d33c997b3a01878c01b554c13fdcd#commitcomment-7953730> and <https://github.com/ricardomv/glfw/commit/a84fe7eb850d33c997b3a01878c01b554c13fdcd#commitcomment-7953719>.

**Comment by ricardomv** [comment]
the issue stated in the comment 7953719 was already fixed here https://github.com/ricardomv/glfw/commit/300550aa756712204dbe5f05c60d794d2f1761b4 but I have rebased the branch on master. I don't know how to fix ricardomv@a84fe7e#commitcomment-7953719

**Comment by jadahl** [comment]
What I meant was the second part of comment 7953719, i.e. the missing close(fd);

Regarding the other issue; we need to track both the DnD objects and selection offers separately, destroying them when they should be destroyed given what type it is. Otherwise we leak memory.

More or less: 1. receive data offer. 2. receive either enter or selection - this determines if its DND or selection/clipboard. 3. upon leave, destroy DND data offer; upon selection, destroy previous selection offer.

The mime-type has nothing to do if its DND or clipboard.

**Comment by ricardomv** [comment]
@jadahl sorry i don't have the time to work on this.

**Comment by jadahl** [comment]
Ok! Thanks anyway. I will leave the pull request open if you find time or if anyone else is interested in continuing.

**Comment by kovidgoyal** [comment]
FYI this is implemented in my glfw fork

**Comment by linkmauve** [comment]
Superseded by #1353.

**Pull request closed without merging**
