### PR TITLE
Win32 maximize for issue #1499

### PR DESCRIPTION
**Pull request by dougbinks**

### CODE REVIEW

**Comment by dougbinks** [comment]
Note that I haven't altered the changelog as that has been removed from the readme.

**Comment by Luflosi** [comment]
This patch uses tabs and I think spaces are the standard in GLFW.

**Comment by dougbinks** [comment]
Spaces are indeed standard, I've switched them.

**Comment by elmindreda** [comment]
This sentence adds cross-links with #1499.

**Comment by elmindreda** [comment]
I won't merge this fix but it did lead me to the cause of #1499 and a bonus bug. Thank you!

At first I thought the fix shouldn't work as the `win32.maximized` boolean is only used for disambiguation inside the `WM_SIZE` handler and isn't set during creation (the bonus bug). #1499 is caused by the content scale adjustment call to `SetWindowPos` during window creation, which both undoes the maximization from creating the window with `WS_MAXIMIZE` and causes the boolean to be updated early enough.

711b9694a133ef338482ae75ada724e3a9915d91 switches to `SetWindowPlacement` for adjusting the normal window rect without breaking initial maximization.

**Comment by dougbinks** [comment]
Excellent fix, good find!

**Pull request closed without merging**
