### PR TITLE
transparent windows

### PR DESCRIPTION
**Pull request by cosier**
Hello! Great library!
I have come across the need for transparent windows _(in dealing with rounded borders for a undecorated window)_

I have looked at the existing issue for transparency options #197 
However it was incomplete, did not compile on OSX, and didn't support X11.

My pull request provides working transparency for both OSX and X11 (not aware of the current state for transparency on Windows **but am willing to work on it next**).

What I have done:

1. Checkout'd @ckaran branch ckaran/transparent_window and made it compile and added some alphaMask struct members here and there for OSX, 
2. Synced it up with the current master.
2. Added some use of XRender _(requires additional linkage on cmake)_ to detect pict_format for alphaMask (maybe there is a better alternative that doesn't require XRender?.

Transparency can be enjoyed with the following glfw hint
`glfwWindowHint(GLFW_TRANSPARENT, GLFW_TRUE)`

This is my first dive in GLFW and the community here, please let me know what I am missing or if anything is needs to be done.

There is an example application called "transparent" in examples/

transparent_window_example_linux
transparent_window_example_osx

### CODE REVIEW

**Comment by cosier** [comment]
Looks like the windows builds are failing on AppVeyor. 
I shall look into it.

**Comment by cosier** [comment]
There was some minor linkage issue with building the transparency demo on Windows.
That has been fixed, however it is lacking transparency _(the most important part!)_.

My guess is that there is no transparency implementation for wgl.
I shall look into that.

**Comment by cosier** [comment]
Luckily, I was pointed to #723 , which already implemented effecient transparency for windows via DWM.
I have merged that into this branch, and we now have windows support as well.

I have tested it on Windows 7 inside a VM.
transparency_demo_windows

**Comment by cosier** [comment]
It seems older MSVC (ie. 2013) does not support the c++ keyword "inline", but rather a vendor specific "__inline". So I just removed it and let the compiler deal with it.

Also after merging with _glfw:transparent-window_ branch, it already contained a transparentified gears.exe demo, thus rendering the transparent.exe demo from another dev branch **redundant**.

I have removed the transparent demo to slim this pull request. 

Currently seeking any other issues...

**Comment by cosier** [comment]
Did some cleanup around duplicant transparent flags for wndconfig and fbconfig.

Since GLFW_TRANSPARENT is a framebuffer flag, I removed the other ones (as it caused additional internal signature changes to pass around the wndconfig).

Merge should slimmer now, and ready for review.

**Comment by elmindreda** [comment]
(This is not the review but) this looks very promising! Thank you!

**Comment by elmindreda** [comment]
@cosier I'm afraid I couldn't merge this directly as the original author metadata of the code you rebased is missing. Instead I put together the (current state of the) `transparent-window` branch, using your work as a guide through all the various revisions and adding your cleanups on top.

Does this look all right? Did I miss or mis-attribute anything?

**Comment by cosier** [comment]
Ah the good ol' git rebase trick.
Looks good, I guess we can close this pull request then :-)

**Comment by bit2shift** [comment]
Wouldn't it be interesting if one were to use the DWM API to extend the frame (`DwmExtendFrameIntoClientArea` with a padding of -1) all way and make the window fuly Aero Glass?
Just dropping my 2 cents (actually 2 function calls, the other being `DwmIsCompositionEnabled()`, which is required for Vista and 7 only).

**Comment by elmindreda** [comment]
@cosier Thank you again so much for this PR! It honestly was immensely helpful for making sense of the backlog.

@bit2shift We can look into that once 3.3 is out. There are platform specific window hints now.

**Pull request closed without merging**
