### PR TITLE
Started adding memory allocation checks

### PR DESCRIPTION
**Pull request by BrettRToomey**
Regarding issue #478, I began by checking all instances of `calloc` for a `NULL` return. As I'm new to this project, I figured there's a chance I did something in a way you don't like, which is why I'm sending the request before I finish cleaning everything up.

### CODE REVIEW

**Comment by shurcooL** [comment]
The formatting looks off. It seems you're using tabs while the rest of the project uses spaces.

**Comment by BrettRToomey** [comment]
Ah, I knew I'd do something like that! My apologies, I'll get right on it!

**Comment by elmindreda** [comment]
The problem with a patch like this is that it'd take me longer to verify than to write it again myself.

**Comment by elmindreda** [comment]
As an example, `strdup` also performs heap allocation but this patch actually calls it in response to allocation failure.

**Comment by andrewrk** [comment]
> The problem with a patch like this is that it'd take me longer to verify than to write it again myself.

Totally agreed. The pull request is a nice gesture but in the end it's kind of a one-person job.

**Comment by elmindreda** [comment]
More than a gesture, I'd say, but unfortunately it's not useful in _this specific_ case.

**Pull request closed without merging**
