### PR TITLE
Need to create the native window before creating the context. Fixes button states

### PR DESCRIPTION
**Pull request by BrandonSchaefer**
As creating the context creates the egl surface.

### CODE REVIEW

**Comment by BrandonSchaefer** [comment]
Also this is fairly critical since you cant run any apps on mir because of it. Im not sure what changed, but now it just creates the mir needed things such as the NATIVE WINDOW before creating to the egl context which requires the NATIVE WINDOW :)

**Comment by BrandonSchaefer** [comment]
I've another bug ... that Ill push to this pull. Fixes button states not being correct (ie. right left right left would fail to get the current button state). Now it works!

**Comment by elmindreda** [comment]
Will review and merge asap. Thanks!

**Comment by elmindreda** [comment]
Thank you! Merged with [updated commit messages](http://chris.beams.io/posts/git-commit/).

**Pull request closed without merging**
