### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Luflosi**

### CODE REVIEW

**Comment by Luflosi** [comment]
I found a couple more typos. Should I amend this commit?

**Comment by linkmauve** [comment]
Yes please. :)

**Comment by Luflosi** [comment]
I found some typos in the `deps` directory. Can I fix those too?

**Comment by elmindreda** [comment]
Those should be reported upstream, imo.

**Comment by Luflosi** [comment]
I'm honestly too lazy to report the typos upstream. I would need to find where all the repos are hosted, read their contributing guidelines and submit patches to each one individually. If anybody wants to do it, here is what `codespell` complained about. Keep in mind that there are false positives.
./deps/nuklear_glfw_gl2.h:151: vertexes ==> vertices
./deps/tinycthread.c:335: pres ==> press
./deps/tinycthread.c:352: pres ==> press
./deps/tinycthread.c:353: pres ==> press
./deps/tinycthread.c:355: pres ==> press
./deps/tinycthread.c:357: pres ==> press
./deps/tinycthread.c:423: pres ==> press
./deps/tinycthread.c:424: pres ==> press
./deps/tinycthread.c:426: pres ==> press
./deps/tinycthread.c:428: pres ==> press
./deps/tinycthread.c:446: pres ==> press
./deps/tinycthread.c:448: pres ==> press
./deps/tinycthread.c:452: pres ==> press
./deps/tinycthread.c:454: pres ==> press
./deps/tinycthread.c:455: pres ==> press
./deps/nuklear.h:694: transistions ==> transitions
./deps/nuklear.h:1081: vertexes ==> vertices
./deps/nuklear.h:1206: vertexes ==> vertices
./deps/nuklear.h:1231: indicies ==> indices
./deps/nuklear.h:1436: visibile ==> visible
./deps/nuklear.h:1437: visibile ==> visible
./deps/nuklear.h:2599: separeted ==> separated
./deps/nuklear.h:2699: collapsable ==> collapsible
./deps/nuklear.h:2700: visibile ==> visible
./deps/nuklear.h:2705: collapsable ==> collapsible
./deps/nuklear.h:2720: collapsable ==> collapsible
./deps/nuklear.h:2745: collapsable ==> collapsible
./deps/nuklear.h:2746: collapsable ==> collapsible
./deps/nuklear.h:2747: collapsable ==> collapsible
./deps/nuklear.h:2748: collapsable ==> collapsible
./deps/nuklear.h:2749: collapsable ==> collapsible
./deps/nuklear.h:2750: collapsable ==> collapsible
./deps/nuklear.h:2751: collapsable ==> collapsible
./deps/nuklear.h:2753: collapsable ==> collapsible
./deps/nuklear.h:2754: collapsable ==> collapsible
./deps/nuklear.h:2760: collapsable ==> collapsible
./deps/nuklear.h:2764: collapsable ==> collapsible
./deps/nuklear.h:2766: collapsable ==> collapsible
./deps/nuklear.h:2786: collapsable ==> collapsible
./deps/nuklear.h:2803: collapsable ==> collapsible
./deps/nuklear.h:2823: collapsable ==> collapsible
./deps/nuklear.h:2825: collapsable ==> collapsible
./deps/nuklear.h:2846: collapsable ==> collapsible
./deps/nuklear.h:2866: collapsable ==> collapsible
./deps/nuklear.h:2898: collapsable ==> collapsible
./deps/nuklear.h:2914: collapsable ==> collapsible
./deps/nuklear.h:3120: modifyable ==> modifiable
./deps/nuklear.h:3121: modifyable ==> modifiable
./deps/nuklear.h:3141: identifaction ==> identification
./deps/nuklear.h:3144: propery ==> property, properly
./deps/nuklear.h:3198: modifing ==> modifying
./deps/nuklear.h:3199: modifing ==> modifying
./deps/nuklear.h:3200: modifing ==> modifying
./deps/nuklear.h:3207: modifing ==> modifying
./deps/nuklear.h:3228: modifing ==> modifying
./deps/nuklear.h:3249: modifing ==> modifying
./deps/nuklear.h:3270: modifing ==> modifying
./deps/nuklear.h:3293: modifing ==> modifying
./deps/nuklear.h:3316: modifing ==> modifying
./deps/nuklear.h:3892: hight ==> height, high
./deps/nuklear.h:4580: vertexes ==> vertices
./deps/nuklear.h:9353: indicies ==> indices
./deps/nuklear.h:9353: vertexes ==> vertices
./deps/nuklear.h:9357: specifing ==> specifying
./deps/nuklear.h:9360: verticies ==> vertices
./deps/nuklear.h:9360: indicies ==> indices
./deps/nuklear.h:12023: tesselate ==> tessellate
./deps/nuklear.h:13067: te ==> the, be
./deps/nuklear.h:13100: nd ==> and, 2nd
./deps/nuklear.h:13110: Te ==> The, be
./deps/nuklear.h:19086: seperator ==> separator
./deps/nuklear.h:19105: seperator ==> separator
./deps/nuklear.h:19105: seperator ==> separator
./deps/nuklear.h:19111: seperator ==> separator
./deps/nuklear.h:19111: seperator ==> separator
./deps/nuklear.h:21158: modifyable ==> modifiable
./deps/nuklear.h:21160: modifyable ==> modifiable
./deps/nuklear.h:25254: separed ==> separated
./deps/nuklear.h:25264: modifyable ==> modifiable
./deps/nuklear.h:25265: formated ==> formatted
./deps/nuklear.h:25271: Modifing ==> Modifying
./deps/nuklear.h:25271: funtions ==> functions
./deps/nuklear.h:25298: boundries ==> boundaries
./deps/nuklear.h:25315: programatic ==> programmatic
./deps/nuklear.h:25324: seperator ==> separator
./deps/nuklear.h:25360: glyphes ==> glyphs
./deps/nuklear.h:25440: commiting ==> committing
./deps/nuklear.h:25446: glyphes ==> glyphs
./deps/nuklear.h:25463: becomming ==> becoming
./deps/nuklear.h:25510: dependend ==> dependent, depended
./deps/mingw/dinput.h:599: Portugese ==> Portuguese
./deps/mingw/dinput.h:603: Portugese ==> Portuguese
./deps/glad/vulkan.h:2974: pEvents ==> prevents
./deps/glad/vulkan.h:2985: pEvent ==> prevent
./deps/glad/gl.h:1837: lod ==> load

Other than that, my PR is complete and can be reviewed.

**Comment by elmindreda** [comment]
Thank you!

**Pull request merged**
